//in stm ide!!!!!

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	//go to rcc register to turn on clk for led
	int* ptr_rcc = (int*)(0x40023800 + 0x30);

	//turn rcc register on
	*ptr_rcc = *ptr_rcc | 8;

	// create pointer to gpio port mode memory
	int* ptr_mode = (int*)(0x40020C00 + 0x00);

	//turn off input mode
	*ptr_mode = *ptr_mode & ~(1<<25);

	//turn on output node
	*ptr_mode = *ptr_mode | (1<<24);

	//create pointer to gpio output register
	int* ptr_out = (int*)(0x40020c00 + 0x14);

	//turn on the led
	*ptr_out = *ptr_out | (1<<12);


    /* Loop forever */
	for(;;);
}
