/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE f ile comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    //main goal: blink red led by converting pin pb2 to output

    //brings me to ahb1 rcc register 0x40023800
    int* ptr_rcc = (int*)(0x40023800 + 0x30);

    //enable ahb1 rcc set bit#1 of (0x40023800 + 0x30) to 1
    *ptr_rcc = *ptr_rcc | (1<<1);

    //point to port b with offset
    int* ptr_portb = (int*) (0x40020400 + 0x00);

    //change portb pinb2 bit5 to 0(turn input mode off)
    *ptr_portb = *ptr_portb & ~(1<<5);

    //change portb pinb2 bit4 to 1(turn output mode on)
    *ptr_portb = *ptr_portb | (1<<4);

    //turn on led by going to gpiob base address with output data register offset
    int* ptr_led = (int*)(0x40020400 + 0x14); 

    //switch the right bit to 1
    *ptr_led = *ptr_led | (1<<2);

    while(1)
    {
      *ptr_led = *ptr_led | (1<<2);
      for (int i = 0; i<1000000;i++);
      
      *ptr_led = *ptr_led & ~(1<<2);
      for (int i = 0; i<1000000;i++);
    }

	 /* Loop forever */
	for(;;);

}
