/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_ADDRESS 0x40023800
#define AHB1_OFFSET 0x30
#define PORTD_OUTPUT 0x40020C00
#define PORTD_OFFSET 0x00
#define PORTD_PIN15 0x14
#define DELAY 123456

int main(void)
{
    //enable rcc clock with ahb1 offset
    int32_t* ptr_rcc = (int32_t*)(RCC_ADDRESS + AHB1_OFFSET);
    //turn the clock bit to 1
    *ptr_rcc = *ptr_rcc | (1<<3);

    //turn on output mode
    int32_t* ptr_dmode = (int32_t*)(PORTD_OUTPUT + PORTD_OFFSET);
    //turn the output/input bits on and off
    *ptr_dmode = *ptr_dmode | (1<<30);
    *ptr_dmode = *ptr_dmode & ~(1<<31);

    //make pointer to gpio port d pin 15
    int32_t* ptr_d15 = (int32_t*)(PORTD_OUTPUT + PORTD_PIN15);

    //make led blink

    while (1)
    {
      *ptr_d15 = *ptr_d15 | (1<<15);
      for (int32_t i = 0; i<DELAY; i++);
      *ptr_d15 = *ptr_d15 & ~(1<<15);
      for (int32_t i = 0; i<DELAY; i++);
    }
    /* Loop forever */
	for(;;);
}
