/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	  //rcc register clock needs to be turned on
	    int* ptr_rcc = (int*)(0x40023800 + 0x30);
	    //activate the bit using a bit mask
	    *ptr_rcc = *ptr_rcc | 8;

	    //create pointer to gpio port D memory
	    int* ptr_mode = (int*)(0x40020C00 + 0x00);

	    //turn off input mode for D pin 12
		*ptr_mode = *ptr_mode & ~(1<<25);
		//turn on output node for D pin 12
		*ptr_mode = *ptr_mode | (1<<24);

	     //turn off input mode for D pin 13
		*ptr_mode = *ptr_mode & ~(1<<27);
		//turn on output node for D pin 13
		*ptr_mode = *ptr_mode | (1<<26);

	     //turn off input mode for D pin 14
		*ptr_mode = *ptr_mode & ~(1<<29);
		//turn on output node for D pin 14
		*ptr_mode = *ptr_mode | (1<<28);

	     //turn off input mode for D pin 15
		*ptr_mode = *ptr_mode & ~(1<<31);
		//turn on output node for D pin 15
		*ptr_mode = *ptr_mode | (1<<30);

	    //create pointers for each pin output
	    int* ptr_outD = (int*)(0x40020c00 + 0x14);

	    while (1)
	    {
	        //turn on the green led (12)
			*ptr_outD = *ptr_outD | (1<<12);
		    for (int i = 1; i<1000000; i++);
			//turn off the green led (12)
			*ptr_outD = *ptr_outD & ~(1<<12);
		    for (int i = 1; i<1000000; i++);

	        //turn on/off the blue led (15)
	        *ptr_outD = *ptr_outD | (1<<15);
		    for (int i = 1; i<1000000; i++);
	        *ptr_outD = *ptr_outD & ~(1<<15);
		    for (int i = 1; i<1000000; i++);

	        //turn on/off the red led (14)
	        *ptr_outD = *ptr_outD | (1<<14);
		    for (int i = 1; i<1000000; i++);
	        *ptr_outD = *ptr_outD & ~(1<<14);
		    for (int i = 1; i<1000000; i++);

	        //turn on/off the orange led (13)
	        *ptr_outD = *ptr_outD | (1<<13);
		    for (int i = 1; i<1000000; i++);
	        *ptr_outD = *ptr_outD & ~(1<<13);
		    for (int i = 1; i<1000000; i++);
	    }

	 /* Loop forever */
	for(;;);

}
