/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//defines to go go into h file
#define DELAY 300000
#define RCC_ADDR 0x40023800
#define AHB1_ENR_OFFSET 0x30

#define GPIOA_BASE_ADDR 0x40020000
#define GPIOB_BASE_ADDR 0x40020400
#define GPIOD_BASE_ADDR 0x40020C00

#define GPIO_MODE_OFFSET 0x00
#define GPIO_OUTPUT 0x14
#define GPIO_INPUT 0x10

//structs to go into h file

typedef struct
{

    uint32_t GPIOA_EN : 1;
    uint32_t GPIOB_EN : 1;
    uint32_t GPIOC_EN : 1;
    uint32_t GPIOD_EN : 1;
    uint32_t GPIOE_EN : 1;
    uint32_t GPIOF_EN : 1;
    uint32_t GPIOG_EN : 1;
    uint32_t GPIOH_EN : 1;
    uint32_t GPIOI_EN : 1;
    uint32_t reserved0 : 3;
    uint32_t CRCEN : 1;
    uint32_t reserved1 : 5;
    uint32_t BKPSRAM_EN : 1;
    uint32_t reserved2 : 1;
    uint32_t CCMDATARM_EN : 1;
    uint32_t DMA1_EN : 1;
    uint32_t DMA2_EN : 1;
    uint32_t reserved3 : 2;
    uint32_t ETHMAC_EN : 1;
    uint32_t ETHMACTX_EN : 1;
    uint32_t ETHMACRX_EN : 1;
    uint32_t ETHMACPTP_EN : 1;
    uint32_t OTGHS_EN : 1;
    uint32_t OTGHSULPI_EN : 1;
    uint32_t reserved4 : 1;

}RCC_AHB1_s;

typedef struct
{
    uint32_t MODER0 : 2;
    uint32_t MODER1 : 2;
    uint32_t MODER2 : 2;
    uint32_t MODER3 : 2;
    uint32_t MODER4 : 2;
    uint32_t MODER5 : 2;
    uint32_t MODER6 : 2;
    uint32_t MODER7 : 2;
    uint32_t MODER8 : 2;
    uint32_t MODER9 : 2;
    uint32_t MODER10 : 2;
    uint32_t MODER11 : 2;
    uint32_t MODER12 : 2;
    uint32_t MODER13 : 2;
    uint32_t MODER14 : 2;
    uint32_t MODER15 : 2;

}GPIO_MODE_s;
typedef struct
{
    uint32_t ODR0 : 1;
    uint32_t ODR1 : 1;
    uint32_t ODR2 : 1;
    uint32_t ODR3 : 1;
    uint32_t ODR4 : 1;
    uint32_t ODR5 : 1;
    uint32_t ODR6 : 1;
    uint32_t ODR7 : 1;
    uint32_t ODR8 : 1;
    uint32_t ODR9 : 1;
    uint32_t ODR10 : 1;
    uint32_t ODR11 : 1;
    uint32_t ODR12 : 1;
    uint32_t ODR13 : 1;
    uint32_t ODR14 : 1;
    uint32_t ODR15 : 1;
    uint32_t reserved : 16;

}GPIO_OUTPUT_DATA_s;

typedef struct
{

    uint32_t IDR0 : 1;
    uint32_t IDR1 : 1;
    uint32_t IDR2 : 1;
    uint32_t IDR3 : 1;
    uint32_t IDR4 : 1;
    uint32_t IDR5 : 1;
    uint32_t IDR6 : 1;
    uint32_t IDR7 : 1;
    uint32_t IDR8 : 1;
    uint32_t IDR9 : 1;
    uint32_t IDR10 : 1;
    uint32_t IDR11 : 1;
    uint32_t IDR12 : 1;
    uint32_t IDR13 : 1;
    uint32_t IDR14 : 1;
    uint32_t IDR15 : 1;
    uint32_t reserved0 : 16;

}GPIO_INPUT_DATA_s;

/*------------------------------------------------------------------------------------------*/

int main(void)
{
	//rcc register clock needs to be turned on
	RCC_AHB1_s* ptr_rcc = (RCC_AHB1_s*)(RCC_ADDR + AHB1_ENR_OFFSET);

	//activate the ports
    ptr_rcc -> GPIOA_EN = 1;
    ptr_rcc -> GPIOB_EN = 1;
	ptr_rcc -> GPIOD_EN = 1;

	//create pointer to gpio port A memory
	GPIO_MODE_s* ptr_amode = (GPIO_MODE_s*)(GPIOA_BASE_ADDR + GPIO_MODE_OFFSET);
    //create pointer to gpio port B memory
    GPIO_MODE_s* ptr_bmode = (GPIO_MODE_s*)(GPIOB_BASE_ADDR + GPIO_MODE_OFFSET);
    //create pointer to gpio port D memory
	GPIO_MODE_s* ptr_dmode = (GPIO_MODE_s*)(GPIOD_BASE_ADDR + GPIO_MODE_OFFSET);

    //turn on input mode and output mode off port a
    ptr_amode -> MODER0 = 00;
    //turn off input mode and ouput mode on for port b
    ptr_bmode -> MODER10 = 01;
	//turn off input mode for D pin 12,13,14,15 & //turn on output node for D pin 12
	ptr_dmode -> MODER15 = 01;
    ptr_dmode -> MODER14 = 01;
    ptr_dmode -> MODER13 = 01;
    ptr_dmode -> MODER12 = 01;

    //create pointers for each pin output mode register
    GPIO_INPUT_DATA_s* ptr_inA = (GPIO_INPUT_DATA_s*)(GPIOA_BASE_ADDR + GPIO_INPUT);
    GPIO_OUTPUT_DATA_s* ptr_outB = (GPIO_OUTPUT_DATA_s*)(GPIOB_BASE_ADDR + GPIO_OUTPUT);
    GPIO_OUTPUT_DATA_s* ptr_outD = (GPIO_OUTPUT_DATA_s*)(GPIOD_BASE_ADDR + GPIO_OUTPUT);

	while (1)
	{
        //read data from button to var
        uint32_t button_sig = (ptr_inA->IDR0 & (1<<0))>>0;

        if (button_sig == 1)
        {
            //turn all leds on
        		for (int i = 0; i<DELAY; i++);
                ptr_outB -> ODR10 = 1;
                ptr_outD -> ODR12 = 1;
                ptr_outD -> ODR13 = 1;
                ptr_outD -> ODR14 = 1;
                ptr_outD -> ODR15 = 1;
                for (int i = 0; i<DELAY; i++);

                //turn all leds off
                for (int i = 0; i<DELAY; i++);
                ptr_outB -> ODR10 = 0;
                ptr_outD -> ODR12 = 0;
                ptr_outD -> ODR13 = 0;
                ptr_outD -> ODR14 = 0;
                ptr_outD -> ODR15 = 0;
                for (int i = 0; i<DELAY; i++);
          }//end if button on while

        else
        {
            //turn all leds off
            ptr_outB -> ODR10 = 0;
            ptr_outD -> ODR12 = 0;
            ptr_outD -> ODR13 = 0;
            ptr_outD -> ODR14 = 0;
            ptr_outD -> ODR15 = 0;
        }//end button off elif
	}//end main while
    /* Loop forever */
	for(;;);
}
